robot1_description:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_link1
    pid: {p: 10000.0, i: 0.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: link1_to_link2
    pid: {p: 15000.0, i: 0.0, d: 400.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: link2_to_link3
    pid: {p: 15000.0, i: 0.0, d: 400.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: link3_to_link4
    pid: {p: 10000.0, i: 0.0, d: 0.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: link4_to_link5
    pid: {p: 10000.0, i: 0.0, d: 0.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: link5_to_link6
    pid: {p: 10000.0, i: 0.0, d: 0.0}
